COLORS: list[str] = [
    "Red",
    "Pink",
    "Purple",
    "DeepPurple",
    "Indigo",
    "Blue",
    "LightBlue",
    "Cyan",
    "Teal",
    "Green",
    "LightGreen",
    "Lime",
    "Yellow",
    "Amber",
    "Orange",
    "DeepOrange",
    "Brown",
    "Gray",
    "BlueGray",
]

LANGUAGES: dict[str, str] = {
    "hindi": "hi",
    "english": "en",
    "punjabi": "pa",
    "telegu": "te",
    "bengali": "bn",
    "marathi": "mr",
}

PALETTE: list[list[float]] = [
    [0.28627450980392155, 0.8431372549019608, 0.596078431372549, 1],
    [0.3568627450980392, 0.3215686274509804, 0.8666666666666667, 1],
    [0.8862745098039215, 0.36470588235294116, 0.592156862745098, 1],
    [0.8784313725490196, 0.9058823529411765, 0.40784313725490196, 1],
]

STATES: dict[str, list[str]] = {
    "Himachal Pradesh": ["Mandi", "Bilaspur", "Kullu", "Chamba", "Shimla", "Hamirpur", "Una", "Sirmore", "Kangra"],
    "Nagaland": ["Kohima"],
    "Meghalaya": ["East Khasi Hills"],
    "Karnataka": [
        "Chitradurga",
        "Shimoga",
        "Dharwad",
        "Koppal",
        "Kolar",
        "Bidar",
        "Haveri",
        "Bagalkot",
        "Karwar(Uttar Kannad)",
        "Mandya",
        "Hassan",
        "Belgaum",
        "Mysore",
        "Mangalore(Dakshin Kannad)",
        "Udupi",
        "Chikmagalur",
        "Tumkur",
        "Bellary",
        "Bangalore",
        "Gulbarga",
        "Raichur",
        "Gadag",
        "Davangere",
    ],
    "Kerala": [
        "Thirssur",
        "Thiruvananthapuram",
        "Kannur",
        "Idukki",
        "Alappuzha",
        "Wayanad",
        "Ernakulam",
        "Kottayam",
        "Palakad",
        "Pathanamthitta",
        "Malappuram",
        "Kozhikode(Calicut)",
        "Kollam",
    ],
    "Chattisgarh": [
        "Bilaspur",
        "Dantewada",
        "Mahasamund",
        "Raigarh",
        "Narayanpur",
        "Koria",
        "Bijapur",
        "Surajpur",
        "Kanker",
        "Dhamtari",
        "Balrampur",
        "Balodabazar",
        "Kabirdham",
        "Janjgir",
        "Surguja",
        "Raipur",
        "Korba",
        "Durg",
        "Rajnandgaon",
    ],
    "Uttar Pradesh": [
        "Banda",
        "Barabanki",
        "Bahraich",
        "Rampur",
        "Sultanpur",
        "Gautam Budh Nagar",
        "Aligarh",
        "Mau(Maunathbhanjan)",
        "Ballia",
        "Khiri (Lakhimpur)",
        "Basti",
        "Sitapur",
        "Kanpur",
        "Pillibhit",
        "Farukhabad",
        "Jyotiba Phule Nagar",
        "Auraiya",
        "Saharanpur",
        "Gonda",
        "Azamgarh",
        "Baghpat",
        "Jhansi",
        "Mahoba",
        "Muradabad",
        "Etah",
        "Raebarelli",
        "Etawah",
        "Badaun",
        "Hardoi",
        "Maharajganj",
        "Firozabad",
        "Lakhimpur",
        "Mainpuri",
        "Meerut",
        "Balrampur",
        "Deoria",
        "Bulandshahar",
        "Mathura",
        "Sant Kabir Nagar",
        "Ghazipur",
        "Bijnor",
        "Muzaffarnagar",
        "Shravasti",
        "Hamirpur",
        "Agra",
        "Bareilly",
        "Hathras",
        "Chandauli",
        "Kaushambi",
        "Chitrakut",
        "Jalaun (Orai)",
        "Fatehpur",
        "Kannuj",
        "Jaunpur",
        "Shahjahanpur",
        "Siddharth Nagar",
        "Mirzapur",
        "Pratapgarh",
        "Lucknow",
        "Unnao",
        "Ghaziabad",
        "Allahabad",
        "Faizabad",
        "Gorakhpur",
        "Ambedkarnagar",
    ],
    "West Bengal": [
        "Birbhum",
        "Coochbehar",
        "Murshidabad",
        "Puruliya",
        "Medinipur(W)",
        "Uttar Dinajpur",
        "Malda",
        "Darjeeling",
        "Bankura",
        "North 24 Parganas",
        "Nadia",
        "Burdwan",
        "Kolkata",
        "Jalpaiguri",
        "Sounth 24 Parganas",
        "Dakshin Dinajpur",
        "Howrah",
    ],
    "Pondicherry": ["Karaikal", "Pondicherry"],
    "Manipur": ["Imphal East", "Imphal West", "Thoubal", "Bishnupur"],
    "Andhra Pradesh": [
        "Kurnool",
        "Visakhapatnam",
        "West Godavari",
        "Vijayanagaram",
        "Chittor",
        "Guntur",
        "East Godavari",
    ],
    "NCT of Delhi": ["Delhi"],
    "Haryana": [
        "Kaithal",
        "Gurgaon",
        "Faridabad",
        "Ambala",
        "Karnal",
        "Mewat",
        "Rohtak",
        "Bhiwani",
        "Sirsa",
        "Rewari",
        "Panchkula",
        "Kurukshetra",
        "Panipat",
        "Mahendragarh-Narnaul",
        "Sonipat",
        "Jind",
    ],
    "Telangana": [
        "Nizamabad",
        "Ranga Reddy",
        "Adilabad",
        "Jagityal",
        "Khammam",
        "Nalgonda",
        "Karimnagar",
        "Warangal",
        "Mahbubnagar",
        "Hyderabad",
        "Medak",
    ],
    "Madhya Pradesh": [
        "Sehore",
        "Ashoknagar",
        "Guna",
        "Jhabua",
        "Dewas",
        "Panna",
        "Indore",
        "Ratlam",
        "Badwani",
        "Shajapur",
        "Raisen",
        "Chhindwara",
        "Ujjain",
        "Rajgarh",
        "Dhar",
        "Neemuch",
        "Hoshangabad",
        "Damoh",
        "Harda",
        "Shivpuri",
        "Mandsaur",
        "Chhatarpur",
        "Narsinghpur",
        "Sheopur",
        "Vidisha",
        "Khargone",
    ],
    "Uttrakhand": ["Nanital", "Dehradoon", "UdhamSinghNagar", "Haridwar"],
    "Tripura": [
        "Khowai",
        "South District",
        "North Tripura",
        "West District",
        "Gomati",
        "Sepahijala",
        "Unokoti",
        "Dhalai",
    ],
    "Tamil Nadu": [
        "Dindigul",
        "Theni",
        "Villupuram",
        "Thanjavur",
        "Cuddalore",
        "Thiruvannamalai",
        "Vellore",
        "Salem",
        "Ariyalur",
        "Namakkal",
        "Erode",
        "Coimbatore",
        "Madurai",
    ],
    "Rajasthan": [
        "Jalore",
        "Tonk",
        "Udaipur",
        "Barmer",
        "Churu",
        "Jodhpur",
        "Dausa",
        "Jaipur",
        "Bundi",
        "Ganganagar",
        "Ajmer",
        "Hanumangarh",
        "Jhalawar",
        "Kota",
        "Baran",
        "Sikar",
        "Chittorgarh",
        "Rajasamand",
    ],
    "Maharashtra": ["Pune"],
    "Bihar": [
        "East Champaran/ Motihari",
        "Bhagalpur",
        "Munghair",
        "Luckeesarai",
        "Rohtas",
        "Muzaffarpur",
        "Chhapra",
        "Khagaria",
        "Kaithar",
        "Kishanganj",
        "Bhojpur",
        "Saharsa",
        "Vaishali",
        "Buxar",
        "Madhubani",
        "Madhepura",
        "Araria",
        "Jamui",
        "Aurangabad",
        "West Chambaran",
        "Nawada",
        "Kaimur/Bhabhua",
        "Sheikhpura",
    ],
    "Jammu and Kashmir": ["Udhampur", "Pulwama", "Srinagar", "Kathua", "Kupwara", "Anantnag", "Jammu"],
    "Chandigarh": ["Chandigarh"],
    "Gujarat": [
        "Banaskanth",
        "Rajkot",
        "Gandhinagar",
        "Junagarh",
        "Jamnagar",
        "Surendranagar",
        "Mehsana",
        "Dahod",
        "Bhavnagar",
        "Bharuch",
        "Patan",
        "Vadodara(Baroda)",
        "Sabarkantha",
        "Morbi",
        "Surat",
        "Anand",
        "Amreli",
        "Porbandar",
        "Ahmedabad",
    ],
    "Goa": ["South Goa"],
    "Punjab": [
        "Faridkot",
        "Mansa",
        "Gurdaspur",
        "Fazilka",
        "Sangrur",
        "Mohali",
        "Patiala",
        "Ferozpur",
        "Muktsar",
        "Ludhiana",
        "Tarntaran",
        "Bhatinda",
        "kapurthala",
        "Amritsar",
        "Ropar (Rupnagar)",
        "Fatehgarh",
        "Hoshiarpur",
        "Jalandhar",
    ],
    "Odisha": [
        "Dhenkanal",
        "Puri",
        "Jagatsinghpur",
        "Nowarangpur",
        "Bhadrak",
        "Balasore",
        "Bargarh",
        "Jajpur",
        "Mayurbhanja",
        "Angul",
        "Nayagarh",
        "Gajapati",
        "Bolangir",
        "Koraput",
        "Sundergarh",
    ],
}

MARKETS: dict[str, list[str]] = {
    "Medak": ["Dubbak", "Gajwel", "Jogipet", "Medak", "Sadasivpet", "Sangareddy", "Siddipet", "Vantamamidi"],
    "Haridwar": ["Bhagwanpur(Naveen Mandi Sthal)", "Haridwar Union", "Roorkee"],
    "Banda": ["Atarra", "Banda"],
    "Faridkot": ["Jaitu", "Kotkapura"],
    "Chitradurga": ["Chitradurga"],
    "Udhampur": ["Reasi"],
    "Nanital": ["Ramnagar"],
    "Thirssur": ["Chavakkad", "Chelakkara", "Mattathur", "Thrissur"],
    "Shimoga": ["Bhadravathi", "Shikaripura", "Shimoga"],
    "Dhenkanal": ["Hindol", "Kamakhyanagar"],
    "Dindigul": ["Gopalpatti", "Natham", "Oddunchairum", "Vadamadurai "],
    "Birbhum": ["Rampurhat", "Sainthia"],
    "Bahraich": ["Bahraich", "Mihipurwa", "Naanpara", "Risia"],
    "East Champaran/ Motihari": ["Motihari", "Raxaul"],
    "Kaithal": ["Cheeka", "Dhand"],
    "Rampur": ["Rampur", "Shahabad", "Tanda(Rampur)", "Vilaspur"],
    "Munghair": ["Munghair"],
    "Gautam Budh Nagar": ["Dankaur"],
    "Khowai": ["Teliamura"],
    "Mau(Maunathbhanjan)": ["Doharighat", "Kopaganj"],
    "Bilaspur": ["Bilaspur", "Ratanpur", "Takhatpur"],
    "Ballia": ["Ballia", "Rasda", "Vilthararoad"],
    "Jalore": ["Jalore"],
    "Khiri (Lakhimpur)": ["Maigalganj", "Mohammdi", "Tikonia"],
    "Theni": ["Cumbum", "Theni"],
    "Villupuram": ["Chinnasalem", "Kallakurichi", "Manalurpet", "Thiryagadurgam", "Tiruvennainallur", "Vikkiravandi"],
    "Gurgaon": ["Sohna"],
    "Kurnool": ["Adoni", "Alur", "Atmakur", "Banaganapalli", "Dhone", "Kurnool", "Nandikotkur"],
    "Kullu": ["Bandrol", "Bhuntar", "Kullu", "Kullu(Chauri Bihal)", "Kullu(Patli Kuhal)"],
    "Basti": ["Basti"],
    "Puri": ["Dumal", "Nimapara"],
    "Thiruvananthapuram": ["Aralamoodu", "Chala"],
    "Tonk": ["Deoli", "Dooni"],
    "Sitapur": ["Mehmoodabad", "Misrikh", "Sindholi", "Sitapur", "Viswan"],
    "Mahasamund": ["Basana"],
    "Farukhabad": ["Farukhabad", "Kamlaganj", "Kayamganj"],
    "Dewas": ["Dewas(F&V)", "Khategaon"],
    "Raigarh": ["Gharghoda", "Raigarh"],
    "Gurdaspur": ["Dera Baba Nanak", "Dinanagar", "Kalanaur"],
    "Gandhinagar": ["Dehgam", "Dehgam(Rekhiyal)", "Kalol", "Kalol(Veg Market Kalol)", "Mansa", "Mansa(Manas Veg Yard)"],
    "Dehradoon": ["Dehradoon", "Rishikesh", "Vikasnagar"],
    "Faridabad": ["Ballabhgarh", "Faridabad"],
    "Muzaffarpur": ["Bhagwanpur Mandi"],
    "Murshidabad": ["Jiaganj", "Kandi", "Lalbagh"],
    "Jamnagar": ["Dhrol"],
    "Saharanpur": ["Chutmalpur", "Gangoh", "Rampurmaniharan", "Saharanpur"],
    "Dharwad": ["Hubli (Amaragol)"],
    "Azamgarh": ["Azamgarh"],
    "Baghpat": ["Bagpat", "Baraut", "Khekda"],
    "Jhansi": ["Baruwasagar", "Gurusarai", "Jhansi", "Mauranipur", "Moth"],
    "Puruliya": ["Purulia"],
    "Karnal": ["Gharaunda", "Nigdu", "Nilokheri"],
    "Koppal": ["Gangavathi", "Kustagi"],
    "Udaipur": ["Udaipur(F&V)"],
    "Indore": ["Mhow", "Sanwer"],
    "Medinipur(W)": ["Garbeta(Medinipur)", "Medinipur(West)"],
    "Muradabad": ["Bhehjoi", "Muradabad", "Sambhal"],
    "Khagaria": ["Khagaria"],
    "Uttar Dinajpur": ["Islampur", "Kaliaganj", "Raiganj"],
    "West District": ["Champaknagar"],
    "Etah": ["Aliganj", "Awagarh", "Etah", "Kasganj"],
    "Barmer": ["Barmer"],
    "Sangrur": ["Ahmedgarh", "Dhuri", "Lehra Gaga"],
    "Pune": ["Pune(Pimpri)"],
    "Koria": ["Manendragarh"],
    "Jajpur": ["Jajpur"],
    "Raebarelli": ["Lalganj", "Raibareilly", "Salon"],
    "Mohali": ["Dera Bassi", "Kharar", "Lalru"],
    "Kannur": ["Irikkur", "Payyannur", "Taliparamba"],
    "Etawah": ["Bharthna", "Etawah", "Jasvantnagar"],
    "Shajapur": ["Kalapipal", "Momanbadodiya", "Nalkehda"],
    "Badaun": ["Babrala", "Badayoun", "Bilsi", "Dataganj", "Shahaswan", "Visoli", "Wazirganj"],
    "Mayurbhanja": ["Betnoti", "Karanjia"],
    "Patan": ["Siddhpur"],
    "Hardoi": ["Hardoi", "Madhoganj"],
    "Shimla": ["Shimla", "Shimla and Kinnaur(Nerwa)", "Shimla and Kinnaur(Rampur)", "Shimla and Kinnaur(Theog)"],
    "UdhamSinghNagar": ["Gadarpur", "Kashipur", "Rudrapur", "Sitarganj"],
    "Maharajganj": ["Anandnagar", "Gadaura", "Nautnava", "Partaval"],
    "Churu": ["Churu"],
    "Mewat": ["FerozpurZirkha(Nagina)", "Punhana", "Taura"],
    "Khammam": ["Bhadrachalam", "Burgampadu", "Kothagudem", "Wyra", "Yellandu"],
    "Kolar": ["Bangarpet", "Chintamani", "Gowribidanoor", "Kolar"],
    "Lakhimpur": ["Lakhimpur"],
    "Idukki": ["Adimali", "Thodupuzha"],
    "Kaithar": ["Barari"],
    "Kanker": ["Charama", "Lakhanpuri", "Narharpur"],
    "Dhamtari": ["Dhamtari", "Nagari"],
    "Mainpuri": ["Bewar", "Ghiraur", "Mainpuri"],
    "Nalgonda": [
        "Aler",
        "Chandur",
        "Chandur(Mungodu)",
        "Chityal",
        "Choutuppal",
        "Devarakonda",
        "Devarkonda(Dindi)",
        "Devarkonda(Mallepalli)",
        "Halia",
        "Huzurnagar",
        "Kodad",
        "Mothkur",
        "Nakrekal",
        "Neredcherla",
        "Ramannapet",
        "Suryapeta",
        "Tirumalagiri",
        "Venkateswarnagar",
        "Venkateswarnagar(Chintapalli)",
        "Voligonda",
    ],
    "Jodhpur": [
        "Jodhpur(F&V)(Bhadwasia)",
        "Jodhpur(F&V)(Paota)",
        "Jodhpur(Grain)(Bhagat Ki Kothi)",
        "Jodhpur (Grain)(Mandor)",
    ],
    "Salem": [
        "Attur",
        "Gangavalli",
        "Karumanturai",
        "Kolathur",
        "Konganapuram",
        "Omalur",
        "Salem",
        "Thalaivasal",
        "Thammampati",
        "Vazhapadi",
    ],
    "Dausa": ["Lalsot", "Lalsot(Mandabari)"],
    "Rajgarh": ["Khilchipur", "Khujner"],
    "Balrampur": ["Balrampur", "Kusmee", "Panchpedwa", "Ramanujganj", "Tulsipur"],
    "Jaipur": ["Chaksu", "Jaipur(Bassi)", "Jaipur(F&V)"],
    "Kishanganj": ["Bahadurganj", "Kishanganj", "Thakurganj"],
    "Bhojpur": ["Bihiya", "Piro"],
    "Mathura": ["Kosikalan", "Mathura"],
    "Vadodara(Baroda)": ["Padra"],
    "Balodabazar": ["Bhatgaon", "Kasdol", "Sarsiwan"],
    "Vaishali": ["Hajipur", "Jaitipir Mandi  Lalganj block", "Parsoniya Mandi  Mahua block"],
    "Karimnagar": [
        "Choppadandi",
        "Dharmapuri",
        "Gangadhara",
        "Gollapally",
        "Gopalraopet",
        "Huzzurabad",
        "Ibrahimpatnam",
        "Jammikunta",
        "Karimnagar",
        "Kataram",
        "Koratla",
        "Mallial(Cheppial)",
        "Manthani",
        "Peddapalli",
        "Pudur",
        "Sultanabad",
        "Vemulawada",
    ],
    "Warangal": ["Cherial", "Kesamudram", "Kodakandal", "Narsampet", "Parkal", "Warangal"],
    "Hoshangabad": ["Bankhedi", "Itarsi"],
    "Ariyalur": ["Ariyalur Market", "Jayamkondam"],
    "Imphal West": ["Imphal"],
    "North 24 Parganas": ["Barasat", "Habra"],
    "Muzaffarnagar": ["Kairana", "Khatauli", "Muzzafarnagar", "Shahpur", "Thanabhawan"],
    "Ajmer": ["Ajmer(F&V)", "Bijay Nagar"],
    "Bolangir": ["Kantabaji"],
    "Ludhiana": ["Doraha", "Khanna", "Ludhiana", "Sahnewal"],
    "Anantnag": ["Ashahipora (Anantnagh)", "Kulgam"],
    "Nadia": ["Chakdah", "Kalyani", "Karimpur", "Ranaghat"],
    "Sabarkantha": ["Himatnagar", "Talod"],
    "Hamirpur": ["Bharuasumerpur", "Hamirpur", "Hamirpur(Nadaun)", "Kurara", "Maudaha", "Muskara"],
    "Harda": ["Harda(F&V)"],
    "Morbi": ["Vankaner", "Vankaner(Sub yard)"],
    "Madhubani": ["Benipatti", "Jainagar", "Madhubani"],
    "Bareilly": ["Anwala", "Bahedi", "Bareilly", "Richha"],
    "East Khasi Hills": ["Mawiong Regulated Market", "Shillong"],
    "Jhalawar": ["Aklera", "Jhalarapatan", "Khanpur"],
    "Shivpuri": ["Barad", "Kolaras", "Pichhour"],
    "Chandauli": ["Chandoli"],
    "Unokoti": ["Pabiacherra"],
    "Bhatinda": ["Bathinda", "Bhucho", "Maur", "Raman", "Talwandi Sabo"],
    "Kota": ["Kota (FV)"],
    "Jalaun (Orai)": ["Ait", "Jalaun", "Madhogarh", "Orai"],
    "Chhatarpur": ["Harpalpur"],
    "kapurthala": ["Sultanpur"],
    "Fatehpur": ["Bindki", "Fatehpur", "Jahanabad", "Khaga", "Kishunpur"],
    "Alappuzha": ["Chengannur", "Harippad", "Kayamkulam"],
    "Rewari": ["Kosli", "Rewari"],
    "Baran": ["Baran", "Chhabra"],
    "Araria": ["Arreria"],
    "Jaunpur": ["Jaunpur", "Mugrabaadshahpur", "Shahganj"],
    "Amreli": ["Babra", "Bagasara", "Damnagar", "Khambha", "Savarkundla"],
    "Hyderabad": ["Bowenpally", "Gaddiannaram", "Gudimalkapur", "Mahboob Manison"],
    "Bidar": ["Basava Kalayana", "Bidar"],
    "Narsinghpur": ["Gadarwada"],
    "Jammu": ["Batote", "Narwal Jammu (F&V)"],
    "Jamui": ["Jamui"],
    "Mirzapur": ["Mirzapur"],
    "Amritsar": ["Amritsar(Amritsar Mewa Mandi)", "Mehta", "Rayya"],
    "Sheopur": ["Sheopurkalan", "Syopurkalan(F&V)"],
    "Pratapgarh": ["Pratapgarh"],
    "Kangra": ["Kangra", "Kangra(Jassour)"],
    "Nawada": ["Rajauli"],
    "Guntur": ["Duggirala"],
    "Namakkal": ["Namagiripettai", "Namakkal", "Rasipuram", "Tiruchengode", "Velur"],
    "Surguja": ["Ambikapur"],
    "Raipur": ["Abhanpur", "Arang"],
    "Lucknow": ["Lucknow"],
    "Unnao": ["Bangarmau", "Purwa"],
    "Kolkata": ["Mechua", "Sealdah Koley Market"],
    "Panipat": ["Samalkha"],
    "Mahendragarh-Narnaul": ["Narnaul"],
    "Haveri": ["Haveri"],
    "Allahabad": ["Ajuha", "Allahabad", "Jasra", "Sirsa"],
    "Porbandar": ["Porbandar"],
    "Thoubal": ["Thoubal"],
    "Jalpaiguri": ["Belacoba", "Dhupguri", "Jalpaiguri Sadar", "Moynaguri"],
    "Dhalai": ["Chowmanu", "Masli"],
    "Bagalkot": ["Bagalakot"],
    "Korba": ["Katghora"],
    "Durg": ["Durg"],
    "Rajnandgaon": ["Bandhabazar", "Rajnandgaon"],
    "Coimbatore": [
        "Anaimalai",
        "Coimbatore",
        "Karamadai",
        "Madathukulam",
        "Palladam",
        "Pollachi",
        "Pongalur",
        "Pudupalayam",
        "Sevur",
        "Thiruppur",
        "Udumalpet",
    ],
    "Khargone": ["Bhikangaon", "Karhi", "Khargone"],
    "Dakshin Dinajpur": ["Balurghat"],
    "Madurai": ["Madurai", "Thirumangalam"],
    "Sehore": ["Ichhawar"],
    "Barabanki": ["Barabanki", "Rudauli", "Safdarganj"],
    "Mandi": ["Mandi(Takoli)"],
    "Pulwama": ["Pulwama (F&V)", "Shopian"],
    "Banaskanth": ["Deesa", "Deesa(Bhildi)", "Dhanera", "Vav"],
    "Karaikal": ["Karaikal"],
    "Bhagalpur": ["Bihpur"],
    "Nizamabad": ["Armoor", "Bhiknoor", "Bodhan", "Gandhari", "Kamareddy", "Madnoor", "Pitlam"],
    "Mansa": ["Boha"],
    "Karwar(Uttar Kannad)": ["Kumta", "Siddapur", "Sirsi"],
    "Sultanpur": ["Jafarganj", "Sultanpur"],
    "Mandya": ["K.R. Pet", "Mandya", "Srirangapattana"],
    "Luckeesarai": ["Lakhisarai"],
    "Aligarh": ["Aligarh", "Atrauli", "Khair"],
    "Kohima": ["Kohima"],
    "Ashoknagar": ["Ashoknagar", "Ashoknagar(F&V)"],
    "Guna": ["Guna(F&V)"],
    "Coochbehar": ["Dinhata", "Mathabhanga", "Toofanganj"],
    "Dantewada": ["Gidam"],
    "Ranga Reddy": ["Chevella", "Ibrahimputnam", "Mehndipatnam(Rythu Bazar)", "Sardarnagar", "Tanduru", "Vikarabad"],
    "Adilabad": ["Asifabad", "Bhainsa", "Boath", "Ichoda", "Jainoor", "Khanapur", "Laxettipet", "Nirmal", "Sarangapur"],
    "Wayanad": ["Kalpetta", "Manathavady"],
    "Ernakulam": ["Aluva", "Ernakulam", "Kothamangalam", "Moovattupuzha", "Perumbavoor", "Piravam", "Thrippunithura"],
    "Hassan": ["Arasikere"],
    "Jhabua": ["Jhabua"],
    "South District": ["Barpathari", "Kalsi"],
    "Imphal East": ["Lamlong Bazaar"],
    "Belgaum": ["Belgaum", "Ramdurga", "Soundati"],
    "North Tripura": ["Dasda"],
    "Thanjavur": ["Kumbakonam", "Papanasam"],
    "Jagatsinghpur": ["Jagatsinghpur"],
    "Rohtas": ["Dehri", "Nokha", "Sasaram"],
    "Kanpur": ["Choubepur", "Jhijhank", "Rura", "Uttaripura", "Varipaal"],
    "Cuddalore": ["Cuddalore", "Kurinchipadi", "Panruti"],
    "Pillibhit": ["Pilibhit", "Puranpur", "Vishalpur"],
    "Chamba": ["Chamba"],
    "Rajkot": ["Dhoraji", "Jasdan", "Rajkot", "Rajkot(Ghee Peeth)"],
    "Panna": ["Ajaygarh", "Panna", "Pawai", "Simariya"],
    "Jyotiba Phule Nagar": ["Dhanura", "Hasanpur"],
    "Auraiya": ["Achalda", "Auraiya", "Dibiapur"],
    "Mysore": ["Hunsur", "Mysore (Bandipalya)", "T. Narasipura"],
    "Junagarh": ["Kodinar", "Mangrol", "Visavadar"],
    "Mangalore(Dakshin Kannad)": ["Bantwala", "Puttur"],
    "Narayanpur": ["Narayanpur"],
    "Gonda": ["Karnailganj", "Nawabganj"],
    "Udupi": ["Karkala"],
    "Ambala": ["Barara", "Naraingarh"],
    "Fazilka": ["Fazilka", "Jalalabad"],
    "Surendranagar": ["Dasada Patadi", "Halvad", "Vadhvan"],
    "Mehsana": [
        "Becharaji",
        "Mehsana(Jornang)",
        "Mehsana(Mehsana Veg)",
        "Unjha",
        "Vijapur",
        "Vijapur(veg)",
        "Visnagar",
    ],
    "Nowarangpur": ["Nawarangpur"],
    "Visakhapatnam": ["Anakapally"],
    "Bhadrak": ["Chandabali"],
    "Balasore": ["Jaleswar", "Nilagiri"],
    "Dahod": ["Dahod", "Dahod(Veg. Market)", "Devgadhbaria"],
    "Chhapra": ["Chhapra"],
    "Mahoba": ["Charkhari", "Mahoba"],
    "Srinagar": ["Ganderbal", "Parimpore"],
    "Chikmagalur": ["Chikkamagalore"],
    "Ratlam": ["Ratlam", "Ratlam(F&V)"],
    "Bargarh": ["Attabira", "Bargarh", "Bargarh(Barapalli)", "Godabhaga"],
    "Badwani": ["Sendhwa"],
    "Thiruvannamalai": [
        "Chethupattu",
        "Cheyyar",
        "Desur",
        "Kilpennathur",
        "Polur(Thiruvannamalai)",
        "Vandavasi",
        "Vettavalam",
    ],
    "Bhavnagar": ["Mahuva(Station Road)"],
    "Pondicherry": ["Madagadipet", "Thattanchavady"],
    "Kathua": ["Kathua"],
    "Bijapur": ["Bharamgarh", "Bhopalpattnam", "Bijapur"],
    "West Godavari": ["Denduluru", "Gopalavaram"],
    "Bharuch": ["Ankleshwar", "Jambusar"],
    "Surajpur": ["Surajpur"],
    "Jagityal": ["Mallapur"],
    "Patiala": ["Dudhansadhan", "Patran"],
    "Tumkur": ["Tiptur", "Tumkur", "Turvekere"],
    "Vellore": ["Vellore"],
    "Raisen": ["Udaipura"],
    "Malda": ["English Bazar", "Gajol"],
    "Firozabad": ["Firozabad", "Sirsaganj"],
    "Angul": ["Angul"],
    "Chhindwara": ["Chaurai", "Chhindwara"],
    "Nayagarh": ["Bahadajholla", "Sarankul"],
    "Meerut": ["Mawana", "Parikshitgarh"],
    "Ujjain": ["Badnagar"],
    "Deoria": ["Barhaj", "Devariya"],
    "Bulandshahar": [
        "Anoop Shahar",
        "Divai",
        "Gulavati",
        "Jahangirabad",
        "Khurja",
        "Sikanderabad",
        "Sikarpur",
        "Siyana",
    ],
    "Darjeeling": ["Darjeeling", "Kalimpong", "Karsiyang(Matigara)", "Siliguri"],
    "Bundi": ["Bundi", "DEI(Bundi)"],
    "Saharsa": ["Saharsa"],
    "Kupwara": ["Bumhama-Kupwara (F&V)"],
    "Sant Kabir Nagar": ["Khalilabad"],
    "Dhar": ["Badnawar", "Gandhwani"],
    "Ghazipur": ["Gazipur", "Jangipura", "Yusufpur"],
    "Bijnor": ["Bijnaur", "Chaandpur", "Haldaur", "Nagina", "Najibabad"],
    "Kottayam": ["Ettumanoor", "Kottayam", "Kuruppanthura"],
    "Kabirdham": ["Kawardha"],
    "Ferozpur": ["Zira"],
    "Palakad": ["Koduvayoor", "Palakkad", "Pattambi"],
    "Neemuch": ["Javad"],
    "Ganganagar": ["Gharsana", "Sriganganagar", "Sriganganagar(F&V)"],
    "Bankura": ["Bankura Sadar", "Bishnupur(Bankura)", "Indus(Bankura Sadar)", "Khatra"],
    "Gajapati": ["Kasinagar", "Parlakhemundi"],
    "Delhi": ["Azadpur", "Flower Market Gazipur"],
    "Damoh": ["Patharia"],
    "Muktsar": ["Bariwala", "Malout"],
    "Shravasti": ["Payagpur"],
    "Gomati": ["Silachhari"],
    "Pathanamthitta": ["Kuttoor", "Ranniangadi"],
    "Vijayanagaram": ["Vijayanagaram"],
    "Buxar": ["Brahmpur"],
    "Rohtak": ["Meham", "Sampla"],
    "Agra": ["Agra", "Fatehabad", "Fatehpur Sikri", "Jagnair", "Khairagarh", "Samsabad"],
    "Bhiwani": ["Tosham"],
    "Hanumangarh": ["Goluwala", "Sangriya"],
    "Janjgir": ["Champa", "Naila"],
    "Hathras": ["Haathras", "Shadabad", "Sikandraraau"],
    "Surat": ["Surat"],
    "Una": ["Santoshgarh", "Una"],
    "Tarntaran": ["Patti"],
    "Sepahijala": ["Bishalgarh", "Boxonagar", "Jumpuijala", "Sonamura"],
    "Mahbubnagar": [
        "Achampet",
        "Amangal",
        "Atmakur",
        "Devarakadra",
        "Kalwakurthy",
        "Kollapur",
        "Mahbubnagar",
        "Makthal",
        "Nagarkurnool",
        "Narayanpet",
        "Shadnagar",
        "Wanaparthy Road(Prbbair)",
    ],
    "Mandsaur": ["Mandsaur", "Mandsaur(F&V)"],
    "Sirsa": ["kalanwali"],
    "Sirmore": ["Nahan", "Paonta Sahib"],
    "Kaushambi": ["Bharwari"],
    "Chitrakut": ["Mau(Chitrakut)"],
    "Anand": ["Anand(Veg Yard Anand)", "Umreth"],
    "Madhepura": ["Murliganj"],
    "Burdwan": ["Asansol", "Durgapur", "Guskara(Burdwan)", "Katwa", "Memari"],
    "Bellary": ["Bellary", "Kottur"],
    "Kannuj": ["Chhibramau(Kannuj)", "Kannauj"],
    "Shahjahanpur": ["Jalalabad", "Puwaha", "Shahjahanpur", "Tilhar"],
    "South Goa": ["Margao"],
    "Malappuram": ["Kottakkal", "Manjeri", "Parappanangadi", "Perinthalmanna"],
    "Kozhikode(Calicut)": ["Mukkom", "Palayam", "Perambra", "Quilandy", "Vengeri(Kozhikode)"],
    "Siddharth Nagar": ["Naugarh", "Sahiyapur"],
    "Bangalore": ["Bangalore", "Binny Mill (F&V)  Bangalore", "Channapatana", "Ramanagara"],
    "Koraput": ["Koraput"],
    "Gulbarga": ["Gulbarga", "Yadgir"],
    "Chittor": ["Chittoor", "Kalikiri", "Punganur", "Vayalapadu"],
    "Aurangabad": ["Daunagar"],
    "Sikar": ["Sikar", "Surajgarh"],
    "Chittorgarh": ["Begu", "Chittorgarh", "Fatehnagar", "Kapasan", "Nimbahera"],
    "West Chambaran": ["Bettiah"],
    "Panchkula": ["Barwala"],
    "Kollam": ["Anchal", "Chathanoor", "Kottarakkara", "Punalur", "Sasthamkotta"],
    "Rajasamand": ["Rajasamand"],
    "Kurukshetra": ["Ladwa", "Pehowa", "Pipli", "Shahabad", "Thanesar"],
    "Ghaziabad": ["Ghaziabad", "Hapur", "Noida"],
    "Erode": [
        "Alangeyam",
        "Dharapuram",
        "Erode",
        "Kangeyam",
        "Kunnathur",
        "Moolanur",
        "Muthur",
        "Perundurai",
        "Vellakkoil",
    ],
    "Vidisha": ["Sironj"],
    "Raichur": ["Lingasugur", "Raichur"],
    "Sonipat": ["Gohana"],
    "Faizabad": ["Faizabad"],
    "Ahmedabad": ["Ahmedabad(Chimanbhai Patal Market Vasana)"],
    "Bishnupur": ["Bishenpur"],
    "Gadag": ["Gadag", "Nargunda"],
    "Chandigarh": ["Chandigarh(Grain/Fruit)"],
    "Sounth 24 Parganas": ["Baruipur(Canning)"],
    "Gorakhpur": ["Chorichora", "Gorakhpur"],
    "Ropar (Rupnagar)": ["Chamkaur Sahib", "Morinda"],
    "Kaimur/Bhabhua": ["Kaimur", "Mohana"],
    "Fatehgarh": ["Bassi Pathana", "Khamano", "Sirhind"],
    "Ambedkarnagar": ["Akbarpur"],
    "Davangere": ["Davangere"],
    "Howrah": ["Ramkrishanpur(Howrah)", "Uluberia"],
    "Hoshiarpur": ["Dasuya", "Garh Shankar", "Tanda Urmur"],
    "Jind": ["Jullana", "Narwana", "Pillukhera", "Safidon", "Uchana"],
    "Jalandhar": ["Bhogpur", "Jalandhar City", "Jalandhar City(Jalandhar)", "Lohian Khas", "Noor Mehal"],
    "Sheikhpura": ["Barbigha", "Shekhpura"],
    "Sundergarh": ["Panposh", "Sargipali"],
    "East Godavari": ["Ravulapelem"],
}

CROPS: dict[str, list[str]] = {
    "crops": [
        "Moath Dal",
        "Sponge gourd",
        "Cloves",
        "Mahua Seed(Hippe seed)",
        "Season Leaves",
        "Paddy(Dhan)(Common)",
        "Hybrid Cumbu",
        "Ghee",
        "Squash(Chappal Kadoo)",
        "Ginger(Green)",
        "Water Melon",
        "Soanf",
        "Wood",
        "Pumpkin",
        "Guava",
        "Cardamoms",
        "Thondekai",
        "Onion",
        "Amaranthus",
        "Goat",
        "Ber(Zizyphus/Borehannu)",
        "T.V. Cumbu",
        "Ridgeguard(Tori)",
        "Round gourd",
        "Cowpea(Veg)",
        "Jack Fruit",
        "Castor Seed",
        "Ground Nut Seed",
        "Seetapal",
        "Chikoos(Sapota)",
        "Sunflower",
        "Tinda",
        "Sweet Potato",
        "Kulthi(Horse Gram)",
        "Mint(Pudina)",
        "Bengal Gram(Gram)(Whole)",
        "Peas Wet",
        "White Peas",
        "Coffee",
        "Broomstick(Flower Broom)",
        "Soapnut(Antawala/Retha)",
        "Safflower",
        "Bunch Beans",
        "Pineapple",
        "Surat Beans (Papadi)",
        "Gur(Jaggery)",
        "Taramira",
        "Orange",
        "Soyabean",
        "Rose(Loose))",
        "Raibel",
        "Kodo Millet(Varagu)",
        "Peas(Dry)",
        "Coconut Oil",
        "Tender Coconut",
        "Lotus Sticks",
        "Copra",
        "Firewood",
        "Leafy Vegetable",
        "Corriander seed",
        "Foxtail Millet(Navane)",
        "Egg",
        "Cowpea (Lobia/Karamani)",
        "Lemon",
        "White Pumpkin",
        "Bottle gourd",
        "Tube Rose(Double)",
        "Colacasia",
        "Elephant Yam (Suran)",
        "Walnut",
        "Grapes",
        "Tube Rose(Single)",
        "Papaya",
        "Mustard Oil",
        "Coriander(Leaves)",
        "Yam",
        "Black pepper",
        "Kartali (Kantola)",
        "Beetroot",
        "Coconut",
        "Long Melon(Kakri)",
        "Chapparad Avare",
        "Green Gram Dal (Moong Dal)",
        "Lime",
        "Jaffri",
        "Carnation",
        "Chilly Capsicum",
        "Methi Seeds",
        "Chrysanthemum(Loose)",
        "Mango (Raw-Ripe)",
        "Avare Dal",
        "Chili Red",
        "Guar",
        "Drumstick",
        "Carrot",
        "Green Peas",
        "Groundnut (Split)",
        "Tomato",
        "Isabgul (Psyllium)",
        "Onion Green",
        "Ajwan",
        "Custard Apple (Sharifa)",
        "Chrysanthemum",
        "Marigold(loose)",
        "Bitter gourd",
        "Cauliflower",
        "Persimon(Japani Fal)",
        "Cucumbar(Kheera)",
        "Turmeric",
        "Linseed",
        "Balekai",
        "Seemebadnekai",
        "Cluster beans",
        "Pear(Marasebu)",
        "Tamarind Seed",
        "Paddy(Dhan)(Basmati)",
        "Beans",
        "Black Gram (Urd Beans)(Whole)",
        "Bengal Gram Dal (Chana Dal)",
        "Plum",
        "Arhar (Tur/Red Gram)(Whole)",
        "Arecanut(Betelnut/Supari)",
        "Pepper ungarbled",
        "Indian Beans (Seam)",
        "Arhar Dal(Tur Dal)",
        "Sweet Pumpkin",
        "Cocoa",
        "Lentil (Masur)(Whole)",
        "Mango",
        "Alasande Gram",
        "Rubber",
        "Wheat",
        "Orchid",
        "Bhindi(Ladies Finger)",
        "Karamani",
        "Gingelly Oil",
        "Jarbara",
        "Black Gram Dal (Urd Dal)",
        "Nutmeg",
        "French Beans (Frasbean)",
        "Tamarind Fruit",
        "Bay leaf (Tejpatta)",
        "Millets",
        "Methi(Leaves)",
        "Kabuli Chana(Chickpeas-White)",
        "Little gourd (Kundru)",
        "Cock",
        "Banana",
        "Kinnow",
        "Masur Dal",
        "Suvarna Gadde",
        "Turnip",
        "Snakeguard",
        "Potato",
        "Lilly",
        "Mustard",
        "Maize",
        "Ginger(Dry)",
        "Groundnut",
        "Karbuja(Musk Melon)",
        "Betal Leaves",
        "Rice",
        "Jowar(Sorghum)",
        "Dry Chillies",
        "Lotus",
        "Green Avare (W)",
        "Turmeric (raw)",
        "Apple",
        "Tapioca",
        "Spinach",
        "Rose(Local)",
        "Cummin Seed(Jeera)",
        "Green Gram (Moong)(Whole)",
        "Fish",
        "Chennangi Dal",
        "Mashrooms",
        "Capsicum",
        "Raddish",
        "Thinai (Italian Millet)",
        "Bajra(Pearl Millet/Cumbu)",
        "Sugar",
        "Duster Beans",
        "Mousambi(Sweet Lime)",
        "Pegeon Pea (Arhar Fali)",
        "Cabbage",
        "Jute",
        "Yam (Ratalu)",
        "Groundnut pods (raw)",
        "Papaya (Raw)",
        "Pomegranate",
        "Banana - Green",
        "Coconut Seed",
        "Gladiolus Cut Flower",
        "Knool Khol",
        "Peas cod",
        "Suva (Dill Seed)",
        "Amla(Nelli Kai)",
        "Barley (Jau)",
        "Brinjal",
        "Pointed gourd (Parval)",
        "Green Chilli",
        "Field Pea",
        "Guar Seed(Cluster Beans Seed)",
        "Amphophalus",
        "Ragi (Finger Millet)",
        "Sesamum(Sesame Gingelly Til)",
        "Cotton",
        "Ashgourd",
        "Alsandikai",
        "Garlic",
    ]
}
